<a target="_blank" href="https://colab.research.google.com/github/lukebarousse/Int_SQL_Data_Analytics_Course/blob/main/Resources/Blank_SQL_Notebook.ipynb">
  <img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/>
</a>

# Blank SQL Notebook

#### Import Libraries & Database

In [1]:
import sys
import pandas as pd
import matplotlib.pyplot as plt
%matplotlib inline

# If running in Google Colab, install PostgreSQL and restore the database
if 'google.colab' in sys.modules:
    # Update package installer
    !sudo apt-get update -qq > /dev/null 2>&1

    # Install PostgreSQL
    !sudo apt-get install postgresql -qq > /dev/null 2>&1

    # Start PostgreSQL service (suppress output)
    !sudo service postgresql start > /dev/null 2>&1

    # Set password for the 'postgres' user to avoid authentication errors (suppress output)
    !sudo -u postgres psql -c "ALTER USER postgres WITH PASSWORD 'password';" > /dev/null 2>&1

    # Create the 'colab_db' database (suppress output)
    !sudo -u postgres psql -c "CREATE DATABASE contoso_100k;" > /dev/null 2>&1

    # Download the PostgreSQL .sql dump
    !wget -q -O contoso_100k.sql https://github.com/lukebarousse/Int_SQL_Data_Analytics_Course/releases/download/v.0.0.0/contoso_100k.sql

    # Restore the dump file into the PostgreSQL database (suppress output)
    !sudo -u postgres psql contoso_100k < contoso_100k.sql > /dev/null 2>&1

    # Shift libraries from ipython-sql to jupysql
    !pip uninstall -y ipython-sql > /dev/null 2>&1
    !pip install jupysql > /dev/null 2>&1

# Load the sql extension for SQL magic
%load_ext sql

# Connect to the PostgreSQL database
%sql postgresql://postgres:password@localhost:5432/contoso_100k

# Enable automatic conversion of SQL results to pandas DataFrames
%config SqlMagic.autopandas = True

# Disable named parameters for SQL magic
%config SqlMagic.named_parameters = "disabled"

# Display pandas number to two decimal places
pd.options.display.float_format = '{:.2f}'.format

Connecting to 'postgresql://postgres:***@localhost:5432/contoso_100k'

In [ ]:
%%sql

select
  DATE_PART ('YEAR', ORDERDATE) :: INTEGER AS ORDER_YEAR,
  ROUND (AVG (EXTRACT (DAY FROM AGE (DELIVERYDATE, ORDERDATE))),2) AS AVG_PROCESSING_TIME,
  ROUND (SUM (s.quantity*s.netprice*s.exchangerate)::numeric, 0) as total_net_revenue
FROM
SALES AS s
WHERE ORDERDATE >= CURRENT_DATE - INTERVAL '5 YEARS'
GROUP BY ORDER_YEAR
ORDER BY ORDER_YEAR
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

4 rows affected.

   order_year avg_processing_time total_net_revenue
0        2021                1.41          14735108
1        2022                1.62          44864557
2        2023                1.75          33108566
3        2024                1.67           8396527

In [ ]:
%%sql

select
  customerkey,
  orderkey,
  linenumber,
  (quantity*netprice*exchangerate) as net_revenue,
  avg (quantity*netprice*exchangerate) over () as avg_net_revenue_all_orders,
  avg (quantity*netprice*exchangerate) over (partition by orderkey) as avg_net_revenue_customer
from
  sales
order by customerkey
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,orderkey,linenumber,net_revenue,avg_net_revenue_all_orders,avg_net_revenue_customer
0,15,2259001,0,2217.41,1032.69,2217.41
1,180,3162018,0,71.36,1032.69,992.45
2,180,1305016,0,525.31,1032.69,525.31
3,180,3162018,1,1913.55,1032.69,992.45
4,185,1613010,0,1395.52,1032.69,1395.52
5,243,505008,0,287.67,1032.69,287.67
6,387,2495044,0,1265.56,1032.69,1265.56
7,387,1451007,1,619.77,1032.69,592.64
8,387,1451007,0,1608.10,1032.69,592.64
9,387,1451007,2,97.05,1032.69,592.64

In [ ]:
%%sql

select
  customerkey as customer,
  orderdate,
  (quantity*netprice*exchangerate) as net_revenue,
  row_number () over
    (partition by customerkey
    order by quantity*netprice*exchangerate desc)
    as order_rank,
  sum (quantity*netprice*exchangerate) over (
    partition by customerkey
    order by orderdate)
    as customer_running_total,
  sum (quantity*netprice*exchangerate) over (
    partition by customerkey)
    as customer_net_revenue,
  (quantity*netprice*exchangerate) / sum (quantity*netprice*exchangerate) over (
    partition by customerkey) * 100 :: integer
    as pct_customer_revenue
from
  sales
order by
  customer,
  ORDERDATE
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customer,orderdate,net_revenue,order_rank,customer_running_total,customer_net_revenue,pct_customer_revenue
0,15,2021-03-08,2217.41,1,2217.41,2217.41,100.00
1,180,2018-07-28,525.31,2,525.31,2510.22,20.93
2,180,2023-08-28,1913.55,1,2510.22,2510.22,76.23
3,180,2023-08-28,71.36,3,2510.22,2510.22,2.84
4,185,2019-06-01,1395.52,1,1395.52,1395.52,100.00
5,243,2016-05-19,287.67,1,287.67,287.67,100.00
6,387,2018-12-21,619.77,3,2370.54,4655.84,13.31
7,387,2018-12-21,1608.10,1,2370.54,4655.84,34.54
8,387,2018-12-21,97.05,7,2370.54,4655.84,2.08
9,387,2018-12-21,45.62,8,2370.54,4655.84,0.98

In [ ]:
%%sql

select
  orderdate,
  orderkey * 10 + linenumber as order_line_number,
  (quantity*netprice*exchangerate) as net_revenue,
  sum (quantity*netprice*exchangerate) over (
    partition by orderdate)
    as daily_net_revenue,
  (quantity*netprice*exchangerate) * 100 /  sum (quantity*netprice*exchangerate) over (
    partition by orderdate) as pct_daily_revenue
from
  sales
order by
  orderdate,
  pct_daily_revenue desc
limit 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10043,2395.10,11640.80,20.58
1,2015-01-01,10061,1552.32,11640.80,13.34
2,2015-01-01,10022,1302.91,11640.80,11.19
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10050,975.16,11640.80,8.38
5,2015-01-01,10021,950.25,11640.80,8.16
6,2015-01-01,10041,578.52,11640.80,4.97
7,2015-01-01,10081,574.05,11640.80,4.93
8,2015-01-01,10001,423.28,11640.80,3.64
9,2015-01-01,10040,263.11,11640.80,2.26

In [ ]:
%%sql

select *,
  100*net_revenue/daily_net_revenue as pct_daily_revenue
from (
select
  orderdate,
  orderkey * 10 + linenumber as order_line_number,
  (quantity*netprice*exchangerate) as net_revenue,
  sum (quantity*netprice*exchangerate) over (
    partition by orderdate)
    as daily_net_revenue
from
  sales
) as revenue_by_day

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,orderdate,order_line_number,net_revenue,daily_net_revenue,pct_daily_revenue
0,2015-01-01,10000,63.49,11640.80,0.55
1,2015-01-01,10001,423.28,11640.80,3.64
2,2015-01-01,10010,108.75,11640.80,0.93
3,2015-01-01,10020,1146.75,11640.80,9.85
4,2015-01-01,10021,950.25,11640.80,8.16
...,...,...,...,...,...
199868,2024-04-20,33980341,914.61,96879.43,0.94
199869,2024-04-20,33980342,150.18,96879.43,0.16
199870,2024-04-20,33980350,147.78,96879.43,0.15
199871,2024-04-20,33980351,2019.62,96879.43,2.08
199872,2024-04-20,33980352,56.83,96879.43,0.06

In [ ]:
%%sql

with cohort_customer as (
select distinct
  customerkey,
  extract ('year' from min (orderdate) over (partition by customerkey)) as cohort_year
from
  sales
)

select
  c.cohort_year,
  extract ('year' from orderdate) as purchase_year,
  sum (s.quantity *  s.netprice * s.exchangerate) as net_revenue
from sales s
left join cohort_customer c on s.customerkey = c.customerkey
group by
  c.cohort_year,
  extract ('year' from orderdate)
order by
  c.cohort_year,
  extract ('year' from orderdate)

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  net_revenue
0         2015          2015   7370979.48
1         2015          2016    392623.48
2         2015          2017    479841.31
3         2015          2018   1069850.87
4         2015          2019   1235991.48
5         2015          2020    386489.60
6         2015          2021    872845.99
7         2015          2022   1569787.72
8         2015          2023   1157633.91
9         2015          2024    356186.62
10        2016          2016   9990990.20
11        2016          2017    497028.11
12        2016          2018   1074607.29
13        2016          2019   1565400.72
14        2016          2020    474087.09
15        2016          2021    964417.85
16        2016          2022   2164681.10
17        2016          2023   1265242.63
18        2016          2024    364066.76
19        2017          2017  12244469.63
20        2017          2018   1407065.13
21        2017          2019   1764716.90
22        2017          2020    625928.03
23        2017          2021   1329858.72
24        2017          2022   2428882.80
25        2017          2023   1714010.18
26        2017          2024    464802.56
27        2018          2018  21115924.55
28        2018          2019   3229188.22
29        2018          2020   1171126.65
30        2018          2021   2201262.39
31        2018          2022   4534295.81
32        2018          2023   3271753.92
33        2018          2024    936833.89
34        2019          2019  24022798.65
35        2019          2020   1295044.99
36        2019          2021   2337594.77
37        2019          2022   4848980.74
38        2019          2023   3440099.20
39        2019          2024    751725.53
40        2020          2020   7265759.44
41        2020          2021   1016399.07
42        2020          2022   1891708.40
43        2020          2023   1435051.04
44        2020          2024    312983.02
45        2021          2021  12635597.87
46        2021          2022   3014082.50
47        2021          2023   2242369.63
48        2021          2024    495686.18
49        2022          2022  24412138.13
50        2022          2023   4237220.04
51        2022          2024   1223450.12
52        2023          2023  14345184.96
53        2023          2024    634143.37
54        2024          2024   2856649.33

In [ ]:
%%sql

with yearly_cohort as (
select distinct
  customerkey,
  extract (year from min (orderdate) over (partition by customerkey)) as cohort_year,
  extract (year from orderdate) as purchase_year
from
  sales
)

select distinct
  cohort_year,
  purchase_year,
  count (customerkey) over (partition by purchase_year, cohort_year) as num_cust
from yearly_cohort
order by
cohort_year,
purchase_year

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

55 rows affected.

   cohort_year purchase_year  num_cust
0         2015          2015      2825
1         2015          2016       126
2         2015          2017       149
3         2015          2018       348
4         2015          2019       388
5         2015          2020       171
6         2015          2021       295
7         2015          2022       600
8         2015          2023       499
9         2015          2024       146
10        2016          2016      3397
11        2016          2017       174
12        2016          2018       374
13        2016          2019       457
14        2016          2020       205
15        2016          2021       336
16        2016          2022       746
17        2016          2023       573
18        2016          2024       183
19        2017          2017      4068
20        2017          2018       473
21        2017          2019       570
22        2017          2020       251
23        2017          2021       450
24        2017          2022       943
25        2017          2023       738
26        2017          2024       246
27        2018          2018      7446
28        2018          2019      1081
29        2018          2020       475
30        2018          2021       779
31        2018          2022      1644
32        2018          2023      1407
33        2018          2024       426
34        2019          2019      7755
35        2019          2020       523
36        2019          2021       873
37        2019          2022      1700
38        2019          2023      1439
39        2019          2024       370
40        2020          2020      3031
41        2020          2021       358
42        2020          2022       694
43        2020          2023       547
44        2020          2024       163
45        2021          2021      4663
46        2021          2022      1051
47        2021          2023       889
48        2021          2024       268
49        2022          2022      9010
50        2022          2023      1764
51        2022          2024       561
52        2023          2023      5890
53        2023          2024       332
54        2024          2024      1402

In [ ]:
%%sql

with total_orders_revenue as (
select
  customerkey,
  (quantity*netprice*exchangerate) as net_revenue,
  count (*) over (partition by customerkey) as total_orders
from
  sales
)

select
  customerkey,
  total_orders,
  avg (net_revenue) as customer_net_revenue
from
  total_orders_revenue
group by
  customerkey,
  total_orders

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey  total_orders  customer_net_revenue
0               15             1               2217.41
1              180             3                836.74
2              185             1               1395.52
3              243             1                287.67
4              387             9                517.32
...            ...           ...                   ...
49482      2099619             8                838.74
49483      2099656            13                800.36
49484      2099697             3                 12.73
49485      2099711             2               3004.34
49486      2099743             3                356.03

[49487 rows x 3 columns]

In [ ]:
%%sql

WITH YEARLY_COHORT AS (
select
  customerkey,
  extract (year from MIN (orderdate)) AS cohort_year,
  SUM(QUANTITY*NETPRICE*EXCHANGERATE) AS CUSTOMER_LTV
FROM
  SALES
GROUP BY
  CUSTOMERKEY
)

SELECT
  *,
  AVG (CUSTOMER_LTV) OVER (PARTITION BY COHORT_YEAR) AS AVG_COHORT_LTV
FROM YEARLY_COHORT
ORDER BY
COHORT_YEAR,
CUSTOMERKEY

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

49487 rows affected.

       customerkey cohort_year  customer_ltv  avg_cohort_ltv
0             4376        2015        182.00         5271.59
1             4403        2015       9530.35         5271.59
2             4925        2015       6078.08         5271.59
3             5729        2015        192.16         5271.59
4             6048        2015       1903.89         5271.59
...            ...         ...           ...             ...
49482      2093965        2024        475.22         2037.55
49483      2095129        2024        156.00         2037.55
49484      2095691        2024        326.00         2037.55
49485      2096470        2024        535.78         2037.55
49486      2097541        2024       1143.15         2037.55

[49487 rows x 4 columns]

In [ ]:
%%sql

WITH COHORT AS (
SELECT
  CUSTOMERKEY,
  EXTRACT (YEAR FROM MIN (ORDERDATE) OVER (PARTITION BY CUSTOMERKEY)) AS COHORT_YEAR
FROM
  SALES
)

SELECT *
FROM COHORT
WHERE COHORT_YEAR > '2020'

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

69222 rows affected.

       customerkey cohort_year
0               15        2021
1              406        2021
2              406        2021
3              545        2023
4              545        2023
...            ...         ...
69217      2099697        2022
69218      2099697        2022
69219      2099743        2022
69220      2099743        2022
69221      2099743        2022

[69222 rows x 2 columns]

In [ ]:
%%sql

SELECT
  CUSTOMERKEY,
  ORDERDATE,
  (QUANTITY*NETPRICE*EXCHANGERATE) AS net_revenue,
  COUNT (*) OVER (
    PARTITION BY CUSTOMERKEY
    ORDER BY ORDERDATE)
    AS RUNNING_ORDER_COUNT,
  AVG (QUANTITY*NETPRICE*EXCHANGERATE) OVER (
    PARTITION BY CUSTOMERKEY
    ORDER BY ORDERDATE)
    AS RUNNING_AVG_REVENUE
FROM
  SALES

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

199873 rows affected.

,customerkey,orderdate,net_revenue,running_order_count,running_avg_revenue
0,15,2021-03-08,2217.41,1,2217.41
1,180,2018-07-28,525.31,1,525.31
2,180,2023-08-28,71.36,3,836.74
3,180,2023-08-28,1913.55,3,836.74
4,185,2019-06-01,1395.52,1,1395.52
...,...,...,...,...,...
199868,2099711,2016-08-13,2067.75,1,2067.75
199869,2099711,2017-08-14,3940.92,2,3004.34
199870,2099743,2022-03-17,375.57,2,234.81
199871,2099743,2022-03-17,94.05,2,234.81
199872,2099743,2023-02-11,598.46,3,356.03

In [ ]:
%%sql

WITH ROW_NUMBERING AS (
SELECT
  ROW_NUMBER () OVER
    (PARTITION BY ORDERDATE
    ORDER BY
      ORDERDATE,
      ORDERKEY,
      LINENUMBER
    ) AS row_number,
  *
FROM
  SALES
)

SELECT  *
FROM ROW_NUMBERING
WHERE ORDERDATE > '2015-01-01'
LIMIT 30

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

30 rows affected.

,row_number,orderkey,linenumber,orderdate,deliverydate,customerkey,storekey,productkey,quantity,unitprice,netprice,unitcost,currencycode,exchangerate
0,1,2000,0,2015-01-02,2015-01-02,1639738,530,1613,5,65.99,59.39,33.65,USD,1.00
1,2,2001,0,2015-01-02,2015-01-15,2085372,999999,2182,2,1237.50,1237.50,410.01,USD,1.00
2,3,2002,0,2015-01-02,2015-01-02,1732602,510,1822,2,22.40,22.40,11.42,USD,1.00
3,4,2002,1,2015-01-02,2015-01-02,1732602,510,49,5,149.96,149.96,68.96,USD,1.00
4,5,2003,0,2015-01-02,2015-01-02,728917,300,1674,2,4.89,4.89,2.49,EUR,0.83
5,6,2003,1,2015-01-02,2015-01-02,728917,300,369,1,1747.50,1555.28,803.60,EUR,0.83
6,7,2004,0,2015-01-02,2015-01-02,1724183,570,1654,2,155.99,155.99,51.68,USD,1.00
7,8,2005,0,2015-01-02,2015-01-02,2054699,480,460,1,749.75,712.26,382.25,USD,1.00
8,1,3000,0,2015-01-03,2015-01-03,1793739,500,108,3,99.74,97.75,45.87,USD,1.00
9,2,3000,1,2015-01-03,2015-01-03,1793739,500,1684,3,11.82,11.00,3.92,USD,1.00
10,3,3001,0,2015-01-03,2015-01-03,1048105,400,1653,3,65.99,60.71,33.65,GBP,0.65
11,4,3002,0,2015-01-03,2015-01-03,1035492,390,143,2,239.99,211.19,122.35,GBP,0.65
12,5,3002,1,2015-01-03,2015-01-03,1035492,390,2098,1,381.00,327.66,194.24,GBP,0.65
13,6,3002,2,2015-01-03,2015-01-03,1035492,390,130,1,160.00,139.20,81.58,GBP,0.65
14,7,3003,0,2015-01-03,2015-01-03,787164,290,1164,1,288.00,288.00,146.83,EUR,0.83
15,8,3004,0,2015-01-03,2015-01-03,758284,290,681,1,302.50,302.50,139.10,EUR,0.83
16,9,3005,0,2015-01-03,2015-01-03,1265697,570,109,3,99.74,99.74,45.87,USD,1.00
17,10,3005,1,2015-01-03,2015-01-03,1265697,570,327,2,223.20,196.42,113.79,USD,1.00
18,11,3006,0,2015-01-03,2015-01-03,2003801,550,1874,2,1363.50,1199.88,627.02,USD,1.00
19,12,3007,0,2015-01-03,2015-01-03,741423,280,1642,3,34.73,34.73,15.97,EUR,0.83
20,13,3007,1,2015-01-03,2015-01-03,741423,280,1591,4,7.60,6.91,3.49,EUR,0.83
21,14,3008,0,2015-01-03,2015-01-03,1614670,530,61,4,135.75,135.75,62.43,USD,1.00
22,15,3008,1,2015-01-03,2015-01-03,1614670,530,181,6,103.20,93.91,47.46,USD,1.00
23,16,3009,0,2015-01-03,2015-01-11,208950,999999,2163,2,97.42,91.58,49.67,CAD,1.17
24,17,3009,1,2015-01-03,2015-01-11,208950,999999,553,4,1747.50,1747.50,803.60,CAD,1.17
25,18,3009,2,2015-01-03,2015-01-11,208950,999999,1427,4,414.00,414.00,190.39,CAD,1.17
26,19,3010,0,2015-01-03,2015-01-03,577093,200,1583,7,8.33,7.42,3.83,EUR,0.83
27,20,3010,1,2015-01-03,2015-01-03,577093,200,157,2,879.99,783.19,404.68,EUR,0.83
28,21,3010,2,2015-01-03,2015-01-03,577093,200,1045,3,940.80,931.39,311.71,EUR,0.83
29,1,5000,0,2015-01-05,2015-01-05,241935,80,94,10,50.55,43.47,25.77,CAD,1.18

In [ ]:
%%sql

SELECT
  CUSTOMERKEY,
  COUNT (*) AS total_orders,
  ROW_NUMBER () OVER (ORDER BY COUNT (*) DESC) AS TOTAL_ORDERS_ROW_NUM,
  RANK () OVER (ORDER BY COUNT (*) DESC) AS TOTAL_ORDERS_RANK,
  DENSE_RANK () OVER (ORDER BY COUNT (*) DESC) AS TOTAL_ORDERS_DENSE_RANK
FROM
  SALES
GROUP BY
  CUSTOMERKEY
LIMIT 10

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

10 rows affected.

,customerkey,total_orders,total_orders_row_num,total_orders_rank,total_orders_dense_rank
0,1834524,31,1,1,1
1,1375597,30,2,2,2
2,249557,27,3,3,3
3,459519,26,4,4,4
4,1495941,26,5,4,4
5,1801215,26,6,4,4
6,1219056,25,7,7,5
7,759419,24,8,8,6
8,1427444,24,9,8,6
9,1876222,24,10,8,6

In [15]:
%%sql

with order_month as (
select
  to_char (orderdate, 'YYYY-MM') as month,
  sum (netprice*quantity*exchangerate) as net_revenue
from
  sales
where
  extract (year from orderdate) = 2023
group by
  month
order by
  month
)

select
  *,
  first_value (net_revenue) over (order by month) as first_month_revenue ,
  last_value (net_revenue) over (order by month rows between unbounded preceding and unbounded following) as last_month_revenue,
  nth_value (net_revenue,3) over (order by month) as nth_month_revenue
from
order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,first_month_revenue,last_month_revenue,nth_month_revenue
0,2023-01,3664431.34,3664431.34,2928550.93,NaN
1,2023-02,4465204.57,3664431.34,2928550.93,NaN
2,2023-03,2244316.52,3664431.34,2928550.93,2244316.52
3,2023-04,1162796.16,3664431.34,2928550.93,2244316.52
4,2023-05,2943005.99,3664431.34,2928550.93,2244316.52
5,2023-06,2864500.03,3664431.34,2928550.93,2244316.52
6,2023-07,2337639.34,3664431.34,2928550.93,2244316.52
7,2023-08,2623919.79,3664431.34,2928550.93,2244316.52
8,2023-09,2622774.85,3664431.34,2928550.93,2244316.52
9,2023-10,2551322.61,3664431.34,2928550.93,2244316.52
10,2023-11,2700103.38,3664431.34,2928550.93,2244316.52
11,2023-12,2928550.93,3664431.34,2928550.93,2244316.52

In [21]:
%%sql

with order_month as (
select
  to_char (orderdate, 'YYYY-MM') as month,
  sum (netprice*quantity*exchangerate) as net_revenue
from
  sales
where
  extract (year from orderdate) = 2023
group by
  month
order by
  month
)

select
  *,
  lag (net_revenue) over (order by month) as previous_month_revenue,
  lead (net_revenue) over (order by month) as next_month_revenue,
  (net_revenue - lag (net_revenue) over (order by month))/lag (net_revenue) over (order by month) *100 as monthly_rev_growth
from
order_month

Running query in 'postgresql://postgres:***@localhost:5432/contoso_100k'

12 rows affected.

,month,net_revenue,previous_month_revenue,next_month_revenue,monthly_rev_growth
0,2023-01,3664431.34,NaN,4465204.57,NaN
1,2023-02,4465204.57,3664431.34,2244316.52,21.85
2,2023-03,2244316.52,4465204.57,1162796.16,-49.74
3,2023-04,1162796.16,2244316.52,2943005.99,-48.19
4,2023-05,2943005.99,1162796.16,2864500.03,153.10
5,2023-06,2864500.03,2943005.99,2337639.34,-2.67
6,2023-07,2337639.34,2864500.03,2623919.79,-18.39
7,2023-08,2623919.79,2337639.34,2622774.85,12.25
8,2023-09,2622774.85,2623919.79,2551322.61,-0.04
9,2023-10,2551322.61,2622774.85,2700103.38,-2.72
10,2023-11,2700103.38,2551322.61,2928550.93,5.83
11,2023-12,2928550.93,2700103.38,NaN,8.46

In [ ]:
%%sql

select
  to_char (orderdate, 'YYYY-MM') as order_month_year
from
  sales
limit 10